export const commits = [
    {
        'sha': 'de3c3649f4d9894b0d85a3dc30912e9954a43242',
        'node_id': 'MDY6Q29tbWl0MTkzMjc5MTcyOmRlM2MzNjQ5ZjRkOTg5NGIwZDg1YTNkYzMwOTEyZTk5NTRhNDMyNDI=',
        'commit': {
            'author': {
                'name': 'derfex',
                'email': 'dm1tr0@mail.ru',
                'date': '2019-06-22T21:17:27Z',
            },
            'committer': {
                'name': 'derfex',
                'email': 'dm1tr0@mail.ru',
                'date': '2019-06-22T21:37:09Z',
            },
            'message': 'Бинарный поиск. Тесты. Начальный набор.',
            'tree': {
                'sha': '8cd08d9e6dadc883c54258bc7d3e228896f162e8',
                'url': 'https://api.github.com/repos/derfex/pure-tasks/git/trees/8cd08d9e6dadc883c54258bc7d3e228896f162e8',
            },
            'url': 'https://api.github.com/repos/derfex/pure-tasks/git/commits/de3c3649f4d9894b0d85a3dc30912e9954a43242',
            'comment_count': 0,
            'verification': {
                'verified': false,
                'reason': 'unsigned',
                'signature': null,
                'payload': null,
            },
        },
        'url': 'https://api.github.com/repos/derfex/pure-tasks/commits/de3c3649f4d9894b0d85a3dc30912e9954a43242',
        'html_url': 'https://github.com/derfex/pure-tasks/commit/de3c3649f4d9894b0d85a3dc30912e9954a43242',
        'comments_url': 'https://api.github.com/repos/derfex/pure-tasks/commits/de3c3649f4d9894b0d85a3dc30912e9954a43242/comments',
        'author': {
            'login': 'derfex',
            'id': 20978398,
            'node_id': 'MDQ6VXNlcjIwOTc4Mzk4',
            'avatar_url': 'https://avatars1.githubusercontent.com/u/20978398?v=4',
            'gravatar_id': '',
            'url': 'https://api.github.com/users/derfex',
            'html_url': 'https://github.com/derfex',
            'followers_url': 'https://api.github.com/users/derfex/followers',
            'following_url': 'https://api.github.com/users/derfex/following{/other_user}',
            'gists_url': 'https://api.github.com/users/derfex/gists{/gist_id}',
            'starred_url': 'https://api.github.com/users/derfex/starred{/owner}{/repo}',
            'subscriptions_url': 'https://api.github.com/users/derfex/subscriptions',
            'organizations_url': 'https://api.github.com/users/derfex/orgs',
            'repos_url': 'https://api.github.com/users/derfex/repos',
            'events_url': 'https://api.github.com/users/derfex/events{/privacy}',
            'received_events_url': 'https://api.github.com/users/derfex/received_events',
            'type': 'User',
            'site_admin': false,
        },
        'committer': {
            'login': 'derfex',
            'id': 20978398,
            'node_id': 'MDQ6VXNlcjIwOTc4Mzk4',
            'avatar_url': 'https://avatars1.githubusercontent.com/u/20978398?v=4',
            'gravatar_id': '',
            'url': 'https://api.github.com/users/derfex',
            'html_url': 'https://github.com/derfex',
            'followers_url': 'https://api.github.com/users/derfex/followers',
            'following_url': 'https://api.github.com/users/derfex/following{/other_user}',
            'gists_url': 'https://api.github.com/users/derfex/gists{/gist_id}',
            'starred_url': 'https://api.github.com/users/derfex/starred{/owner}{/repo}',
            'subscriptions_url': 'https://api.github.com/users/derfex/subscriptions',
            'organizations_url': 'https://api.github.com/users/derfex/orgs',
            'repos_url': 'https://api.github.com/users/derfex/repos',
            'events_url': 'https://api.github.com/users/derfex/events{/privacy}',
            'received_events_url': 'https://api.github.com/users/derfex/received_events',
            'type': 'User',
            'site_admin': false,
        },
        'parents': [
            {
                'sha': 'd8c824ee1acced9d4454fd7a2731f8347b7795e3',
                'url': 'https://api.github.com/repos/derfex/pure-tasks/commits/d8c824ee1acced9d4454fd7a2731f8347b7795e3',
                'html_url': 'https://github.com/derfex/pure-tasks/commit/d8c824ee1acced9d4454fd7a2731f8347b7795e3',
            },
        ],
    },
    {
        'sha': 'd8c824ee1acced9d4454fd7a2731f8347b7795e3',
        'node_id': 'MDY6Q29tbWl0MTkzMjc5MTcyOmQ4YzgyNGVlMWFjY2VkOWQ0NDU0ZmQ3YTI3MzFmODM0N2I3Nzk1ZTM=',
        'commit': {
            'author': {
                'name': 'derfex',
                'email': 'dm1tr0@mail.ru',
                'date': '2019-06-22T21:02:49Z',
            },
            'committer': {
                'name': 'derfex',
                'email': 'dm1tr0@mail.ru',
                'date': '2019-06-22T21:02:49Z',
            },
            'message': 'Initial commit',
            'tree': {
                'sha': 'a4e19e5b3b89c8c1dc5c4e8cb8759dbc8123ced9',
                'url': 'https://api.github.com/repos/derfex/pure-tasks/git/trees/a4e19e5b3b89c8c1dc5c4e8cb8759dbc8123ced9',
            },
            'url': 'https://api.github.com/repos/derfex/pure-tasks/git/commits/d8c824ee1acced9d4454fd7a2731f8347b7795e3',
            'comment_count': 0,
            'verification': {
                'verified': false,
                'reason': 'unsigned',
                'signature': null,
                'payload': null,
            },
        },
        'url': 'https://api.github.com/repos/derfex/pure-tasks/commits/d8c824ee1acced9d4454fd7a2731f8347b7795e3',
        'html_url': 'https://github.com/derfex/pure-tasks/commit/d8c824ee1acced9d4454fd7a2731f8347b7795e3',
        'comments_url': 'https://api.github.com/repos/derfex/pure-tasks/commits/d8c824ee1acced9d4454fd7a2731f8347b7795e3/comments',
        'author': {
            'login': 'derfex',
            'id': 20978398,
            'node_id': 'MDQ6VXNlcjIwOTc4Mzk4',
            'avatar_url': 'https://avatars1.githubusercontent.com/u/20978398?v=4',
            'gravatar_id': '',
            'url': 'https://api.github.com/users/derfex',
            'html_url': 'https://github.com/derfex',
            'followers_url': 'https://api.github.com/users/derfex/followers',
            'following_url': 'https://api.github.com/users/derfex/following{/other_user}',
            'gists_url': 'https://api.github.com/users/derfex/gists{/gist_id}',
            'starred_url': 'https://api.github.com/users/derfex/starred{/owner}{/repo}',
            'subscriptions_url': 'https://api.github.com/users/derfex/subscriptions',
            'organizations_url': 'https://api.github.com/users/derfex/orgs',
            'repos_url': 'https://api.github.com/users/derfex/repos',
            'events_url': 'https://api.github.com/users/derfex/events{/privacy}',
            'received_events_url': 'https://api.github.com/users/derfex/received_events',
            'type': 'User',
            'site_admin': false,
        },
        'committer': {
            'login': 'derfex',
            'id': 20978398,
            'node_id': 'MDQ6VXNlcjIwOTc4Mzk4',
            'avatar_url': 'https://avatars1.githubusercontent.com/u/20978398?v=4',
            'gravatar_id': '',
            'url': 'https://api.github.com/users/derfex',
            'html_url': 'https://github.com/derfex',
            'followers_url': 'https://api.github.com/users/derfex/followers',
            'following_url': 'https://api.github.com/users/derfex/following{/other_user}',
            'gists_url': 'https://api.github.com/users/derfex/gists{/gist_id}',
            'starred_url': 'https://api.github.com/users/derfex/starred{/owner}{/repo}',
            'subscriptions_url': 'https://api.github.com/users/derfex/subscriptions',
            'organizations_url': 'https://api.github.com/users/derfex/orgs',
            'repos_url': 'https://api.github.com/users/derfex/repos',
            'events_url': 'https://api.github.com/users/derfex/events{/privacy}',
            'received_events_url': 'https://api.github.com/users/derfex/received_events',
            'type': 'User',
            'site_admin': false,
        },
        'parents': [],
    },
];
